# <font color='blue'>Data Science Academy - Python Fundamentos - Capítulo 8</font>

## Download: http://github.com/dsacademybr

### Exercícios Sobre Módulos Python Para Análise de Dados

### ****** ATENÇÃO ******
### Alguns dos exercícios podem requerer pesquisa adicional na documentação dos pacotes. Pesquise!

### Exercício 1

In [25]:
# Crie um array NumPy com 1000000 e uma lista com 1000000.
# Multiplique cada elemento do array e da lista por 2 e calcule o tempo de execução com cada um dos objetos (use %time).
# Qual objeto oferece melhor performance, array NumPy ou lista?
import numpy as np

array = np.arange(1000000)
lista    = list(range(1000000))

%time array_x2 = array*2
%time lista_x2 = [2*x for x in lista]

Wall time: 4.99 ms
Wall time: 102 ms


## Conclusão: Array numpy são bem mais performáticos do que listas Python

### Exercício 2

In [ ]:
# Exercício 2
# Crie um array de 10 elementos
# Altere o valores de todos os elementos dos índices 5 a 8 para 0

array_10elementos = np.arange(10)
array_10elementos[5:8] = 0
print (array_10elementos)

### Exercício 3

In [27]:
# Crie um array de 3 dimensões e imprima a dimensão 1 
temp = np.arange(125)
array_3d = temp.reshape(5,5,5)
array_3d[0]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### Exercício 4

In [30]:
# Crie um array de duas dimensões (matriz).
matrix = np.arange(25).reshape(5,5)
print ("Matrix:")
print(matrix)
# Imprima os elementos da terceira linha da matriz
print ("Terceira linha:")
print(matrix[2,:])
# Imprima todos os elementos da primeira e segunda linhas e segunda e terceira colunas
print ("Elementos da primeira e segunda linhas e segunda e terceira colunas:")
print(matrix[0:2,1:3])

Matrix:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Terceira linha:
[10 11 12 13 14]
Elementos da primeira e segunda linhas e segunda e terceira colunas:
[[1 2]
 [6 7]]


### Exercício 5

In [31]:
import numpy as np
# Calcule a transposta da matriz abaixo
arr = np.arange(15).reshape((3, 5))

transposta = arr.transpose()
transposta

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

### Exercício 6

In [32]:
# Considere os 3 arrays abaixo
# Retorne o valor do array xarr se o valor for True no array cond. Caso contrário, retorne o valor do array yarr.
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

arr = np.zeros(len(xarr))
for i in range(len(cond)):
    if cond[i] == True:
        arr[i] = xarr[i]
    else:
        arr[i] = yarr[i]        

print (arr)        

[1.1 2.2 1.3 1.4 2.5]


### Exercício 7

In [ ]:
# Crie um array A com 10 elementos e salve o array em disco com a extensão npy
# Depois carregue o array do disco no array B
arr = np.arange(10)
np.save('array_10_elementos', arr)

b = np.load('array_10_elementos.npy')
print (b)

### Exercício 8

In [ ]:
# Considerando a série abaixo, imprima os valores únicos na série
import pandas as pd
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c', 'a', 'b'])
print(obj.unique())

### Exercício 9

In [6]:
# Considerando o trecho de código que conecta em uma url na internet, imprima o dataframe conforme abaixo.
import requests
import pandas as pd

url = 'https://api.github.com/repos/pandas-dev/pandas/issues'
resp = requests.get(url)
resp_list = resp.json()

numbers = []
titles = []
labels = []
states = []

for item in resp_list:
    numbers.append(item['number'])
    titles.append(item['title'])
    labels.append(item['labels'])
    states.append(item['state'])

data = {'number': numbers, 'title': titles, 'label': labels, 'state': states}
df = pd.DataFrame(data)

TypeError: string indices must be integers

In [3]:
df

NameError: name 'df' is not defined

### Exercício 10

In [3]:
# Crie um banco de dados no SQLite, crie uma tabela, insira registros, 
# consulte a tabela e retorne os dados em dataframe do Pandas
!pip install names
import os
import random
import names
import pandas as pd

#os.remove("exercicio10.db") if os.path.exists("exercicio10.db") else None

import sqlite3
# Cria uma conexão
conn = sqlite3.connect("exercicio10.db")

#Cria um curso
c = conn.cursor()

# Cria tabela
def create_table():
    c.execute('CREATE TABLE IF NOT EXISTS PLAYERS(\
                player_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,\
                player_name TEXT,\
                player_score FLOAT)')

# Insere dado aleatório
def data_insert_random():    
    player_name = names.get_full_name()
    player_score = random.random()*1000
    c.execute('insert into players (player_name, player_score) VALUES(?, ?)', (player_name, player_score))
    conn.commit()
    
# Faz leitura de todo banco de dados
def read_db_data():
    c.execute('SELECT * FROM PLAYERS')
    data = c.fetchall()
    return data
    
#create_table()
#for i in range(1000):
#    data_insert_random()
    
data = read_db_data()


df = pd.DataFrame(data, columns = ['id','name','score'])

c.close()
conn.close()
             

In [4]:
df

id                   name       score
0        1           Jodie Alford  724.395246
1        2            Maria Haigh  384.156556
2        3         Jean Alexander  292.088023
3        4             Ruth Simon  298.928908
4        5             Ray Keeler  153.355112
5        6  Georgette Chamberlain  720.732781
6        7         Kenneth Norton  357.886350
7        8       Dustin Crosswell  279.583971
8        9           Lloyd Brooks  918.383095
9       10           Kevin Wright  984.992103
10      11        Michelle Espino  111.833091
11      12      Joanna Washington  347.818157
12      13            April Toner   27.985479
13      14          John Lundberg  869.926339
14      15           Clora Phipps  582.578402
15      16          Maud Mccollum  945.410517
16      17          Robert Murphy   80.590353
17      18           Otis Johnson  736.756296
18      19          Richard Guzma  223.704312
19      20          Sandra Bishop  832.180889
20      21           Shannon Metz  105.333642
21      22     Alicia Heidebrecht  865.320052
22      23           Madge Rhodes  380.015643
23      24         Ruth Nathaniel  366.256366
24      25        Catherine Swing  450.889877
25      26     Lawrence Neighbors  495.060465
26      27           Marta Blaine  263.532592
27      28           Sharon Boyle  843.475878
28      29        Larry Firestine  879.662561
29      30        Travis Villiard  148.098596
...    ...                    ...         ...
1970  1971           Evelyn Platt  844.687840
1971  1972           Kristi Gomes  784.818506
1972  1973           Robert Stone  714.422414
1973  1974           Jana Bradley  540.795256
1974  1975             Carol Kemp  737.830272
1975  1976      Barbara Livermore  592.041881
1976  1977               Kay Cook  273.931056
1977  1978          Dale Williams  857.434289
1978  1979           Vivian Varos  566.197173
1979  1980        Michael Denning  422.083686
1980  1981           Billy Rogers  280.371750
1981  1982         Wendy Figueroa  272.899596
1982  1983          Helen Mancuso   89.268067
1983  1984         Joseph Parsons  302.820890
1984  1985           Sarah Larsen  797.903929
1985  1986        Hubert Rothwell  421.032951
1986  1987          Joseph Austin  106.629780
1987  1988          Michael Keene  931.553767
1988  1989         Mary Cervantez  918.706554
1989  1990            Laura Clark  576.675038
1990  1991         Robert Mullane  530.295061
1991  1992  Christopher Alexander  446.885228
1992  1993             Harry Bell  228.261376
1993  1994         Barbara Cooper  470.833374
1994  1995         Stephen Ripple  708.824584
1995  1996             Ethel Cook  113.142360
1996  1997              Anna Bond  488.715483
1997  1998          Michael Davis  507.552801
1998  1999          John Figueroa  969.152209
1999  2000       Everett Hinojosa  151.388485

[2000 rows x 3 columns]

# Fim

### Obrigado - Data Science Academy - <a href="http://facebook.com/dsacademybr">facebook.com/dsacademybr</a>